#############################################################################
# Makefile for building: Zahoreni_zdroju
# Generated by qmake (3.1) (Qt 6.3.1)
# Project:  Zahoreni_zdroju.pro
# Template: app
# Command: D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\bin\qmake.exe -o Makefile Zahoreni_zdroju.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = Zahoreni_zdroju_resource.res
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: $(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: $(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: Zahoreni_zdroju.pro D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\win32-msvc\qmake.conf D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\spec_pre.prf \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\common\windows-desktop.conf \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\win32\windows_vulkan_sdk.prf \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\common\windows-vulkan.conf \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\common\msvc-desktop.conf \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\qconfig.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_ext_freetype.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_ext_libjpeg.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_ext_libpng.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3danimation.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3danimation_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dcore.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dcore_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dextras.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dextras_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dinput.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dinput_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dlogic.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dlogic_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dquick.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dquick_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dquickanimation.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dquickextras.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dquickinput.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dquickrender.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3drender.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3drender_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_androidautomotiveactivityview.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_androidautomotiveactivityview_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_charts.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_charts_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_chartsqml.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_chartsqml_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_concurrent.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_concurrent_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_core.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_core5compat.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_core5compat_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_core_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_datavisualization.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_datavisualization_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_datavisualizationqml.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_datavisualizationqml_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_dbus.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_dbus_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_designer.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_designer_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_designercomponents_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_entrypoint_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_fb_support_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_flowview.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_flowview_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_freetype_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_gui.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_gui_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_harfbuzz_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_help.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_help_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_jpeg_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_labsanimation.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_labsanimation_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_labsfolderlistmodel.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_labsfolderlistmodel_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_labsqmlmodels.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_labsqmlmodels_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_labssettings.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_labssettings_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_labssharedimage.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_labssharedimage_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_labswavefrontmesh.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_labswavefrontmesh_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_linguist.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_linguist_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_multimedia.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_multimedia_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_multimediaquick_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_multimediawidgets.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_network.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_network_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_networkauth.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_networkauth_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_opengl.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_opengl_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_openglwidgets.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_openglwidgets_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_png_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_printsupport.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_printsupport_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qml.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qml_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmlcompiler_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmlcore.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmlcore_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmldebug_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmldom_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmlintegration.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmlintegration_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmllint_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmllocalstorage.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmllocalstorage_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmlmodels.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmlmodels_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmltest.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmltest_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmlworkerscript.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmlworkerscript_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmlxmllistmodel.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmlxmllistmodel_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3d.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3d_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3dassetimport.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3dassetimport_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3dassetutils.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3dassetutils_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3deffects.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3deffects_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3dglslparser_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3dhelpers.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3dhelpers_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3diblbaker.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3diblbaker_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3dparticleeffects.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3dparticleeffects_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3dparticles.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3dparticles_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3druntimerender.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3druntimerender_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3dutils.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3dutils_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickcontrols2.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickcontrols2impl.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickcontrols2impl_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickcontrolstestutilsprivate_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickdialogs2.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickdialogs2_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickdialogs2quickimpl.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickdialogs2quickimpl_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickdialogs2utils.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickdialogs2utils_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quicklayouts.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quicklayouts_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickparticles_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickshapes_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickstudioapplication.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickstudioapplication_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickstudiocomponents.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickstudiocomponents_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickstudioeffects.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickstudioeffects_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickstudioeventsimulator.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickstudioeventsimulator_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickstudioeventsystem.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickstudioeventsystem_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickstudiologichelper.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickstudiologichelper_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickstudiomultitext.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickstudiomultitext_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quicktemplates2.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quicktestutilsprivate_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quicktimeline.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quicktimeline_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickultralitestudioextras.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickultralitestudioextras_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickultralitestudiolayers.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickultralitestudiolayers_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickwidgets.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_remoteobjects.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_remoteobjectsqml.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_remoteobjectsqml_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_repparser.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_repparser_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_scxml.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_scxml_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_scxmlqml.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_scxmlqml_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_sensors.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_sensors_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_sensorsquick.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_sensorsquick_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_shadertools.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_shadertools_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_sql.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_sql_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_statemachine.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_statemachine_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_statemachineqml.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_statemachineqml_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_svg.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_svg_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_svgwidgets.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_svgwidgets_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_testlib.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_testlib_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_tools_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_uiplugin.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_uitools.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_uitools_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_virtualkeyboard.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_virtualkeyboard_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_webchannel.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_webchannel_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_webenginecore.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_webenginecore_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_webenginequick.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_webenginequick_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_webenginequickdelegatesqml.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_webenginequickdelegatesqml_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_webenginewidgets.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_websockets.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_websockets_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_webview.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_webview_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_webviewquick.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_webviewquick_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_widgets.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_widgets_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_xml.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_xml_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_zlib_private.pri \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\qt_functions.prf \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\qt_config.prf \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\win32-msvc\qmake.conf \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\spec_post.prf \
		.qmake.stash \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\exclusive_builds.prf \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\common\msvc-version.conf \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\toolchain.prf \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\default_pre.prf \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\win32\default_pre.prf \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\resolve_config.prf \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\exclusive_builds_post.prf \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\default_post.prf \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\entrypoint.prf \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\precompile_header.prf \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\warn_on.prf \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\qt.prf \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\resources_functions.prf \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\resources.prf \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\moc.prf \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\win32\opengl.prf \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\uic.prf \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\qmake_use.prf \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\file_copies.prf \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\win32\windows.prf \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\testcase_targets.prf \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\exceptions.prf \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\yacc.prf \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\lex.prf \
		Zahoreni_zdroju.pro \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\lib\Qt6PrintSupport.prl \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\lib\Qt6Widgets.prl \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\lib\Qt6Gui.prl \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\lib\Qt6Core.prl \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\lib\Qt6EntryPoint.prl \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\build_pass.prf \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\lib\Qt6PrintSupportd.prl \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\lib\Qt6Widgetsd.prl \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\lib\Qt6Guid.prl \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\lib\Qt6Cored.prl \
		D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\lib\Qt6EntryPointd.prl
	$(QMAKE) -o Makefile Zahoreni_zdroju.pro
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\spec_pre.prf:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\common\windows-desktop.conf:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\win32\windows_vulkan_sdk.prf:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\common\windows-vulkan.conf:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\common\msvc-desktop.conf:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\qconfig.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_ext_freetype.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_ext_libjpeg.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_ext_libpng.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3danimation.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3danimation_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dcore.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dcore_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dextras.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dextras_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dinput.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dinput_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dlogic.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dlogic_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dquick.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dquick_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dquickanimation.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dquickextras.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dquickextras_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dquickinput.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dquickinput_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dquickrender.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dquickrender_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dquickscene2d.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3drender.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_3drender_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_androidautomotiveactivityview.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_androidautomotiveactivityview_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_charts.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_charts_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_chartsqml.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_chartsqml_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_concurrent.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_concurrent_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_core.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_core5compat.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_core5compat_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_core_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_datavisualization.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_datavisualization_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_datavisualizationqml.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_datavisualizationqml_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_dbus.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_dbus_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_designer.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_designer_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_designercomponents_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_entrypoint_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_fb_support_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_flowview.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_flowview_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_freetype_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_gui.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_gui_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_harfbuzz_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_help.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_help_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_jpeg_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_labsanimation.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_labsanimation_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_labsfolderlistmodel.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_labsfolderlistmodel_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_labsqmlmodels.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_labsqmlmodels_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_labssettings.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_labssettings_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_labssharedimage.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_labssharedimage_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_labswavefrontmesh.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_labswavefrontmesh_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_linguist.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_linguist_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_multimedia.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_multimedia_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_multimediaquick_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_multimediawidgets.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_network.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_network_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_networkauth.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_networkauth_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_opengl.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_opengl_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_openglwidgets.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_openglwidgets_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_packetprotocol_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_png_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_printsupport.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_printsupport_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qml.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qml_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmlcompiler_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmlcore.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmlcore_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmldebug_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmldom_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmlintegration.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmlintegration_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmllint_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmllocalstorage.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmllocalstorage_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmlmodels.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmlmodels_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmltest.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmltest_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmlworkerscript.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmlworkerscript_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmlxmllistmodel.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_qmlxmllistmodel_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3d.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3d_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3dassetimport.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3dassetimport_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3dassetutils.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3dassetutils_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3deffects.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3deffects_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3dglslparser_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3dhelpers.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3dhelpers_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3diblbaker.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3diblbaker_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3dparticleeffects.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3dparticleeffects_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3dparticles.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3dparticles_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3druntimerender.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3druntimerender_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3dutils.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick3dutils_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quick_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickcontrols2.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickcontrols2impl.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickcontrols2impl_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickcontrolstestutilsprivate_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickdialogs2.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickdialogs2_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickdialogs2quickimpl.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickdialogs2quickimpl_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickdialogs2utils.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickdialogs2utils_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quicklayouts.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quicklayouts_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickparticles_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickshapes_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickstudioapplication.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickstudioapplication_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickstudiocomponents.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickstudiocomponents_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickstudioeffects.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickstudioeffects_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickstudioeventsimulator.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickstudioeventsimulator_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickstudioeventsystem.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickstudioeventsystem_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickstudiologichelper.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickstudiologichelper_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickstudiomultitext.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickstudiomultitext_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quicktemplates2.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quicktestutilsprivate_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quicktimeline.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quicktimeline_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickultralitestudioextras.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickultralitestudioextras_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickultralitestudiolayers.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickultralitestudiolayers_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickwidgets.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_quickwidgets_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_remoteobjects.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_remoteobjects_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_remoteobjectsqml.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_remoteobjectsqml_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_repparser.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_repparser_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_scxml.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_scxml_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_scxmlqml.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_scxmlqml_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_sensors.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_sensors_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_sensorsquick.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_sensorsquick_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_shadertools.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_shadertools_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_sql.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_sql_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_statemachine.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_statemachine_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_statemachineqml.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_statemachineqml_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_svg.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_svg_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_svgwidgets.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_svgwidgets_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_testlib.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_testlib_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_tools_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_uiplugin.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_uitools.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_uitools_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_virtualkeyboard.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_virtualkeyboard_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_webchannel.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_webchannel_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_webenginecore.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_webenginecore_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_webenginequick.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_webenginequick_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_webenginequickdelegatesqml.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_webenginequickdelegatesqml_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_webenginewidgets.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_websockets.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_websockets_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_webview.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_webview_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_webviewquick.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_webviewquick_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_widgets.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_widgets_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_xml.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_xml_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\modules\qt_lib_zlib_private.pri:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\qt_functions.prf:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\qt_config.prf:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\win32-msvc\qmake.conf:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\spec_post.prf:
.qmake.stash:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\exclusive_builds.prf:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\common\msvc-version.conf:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\toolchain.prf:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\default_pre.prf:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\win32\default_pre.prf:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\resolve_config.prf:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\exclusive_builds_post.prf:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\default_post.prf:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\entrypoint.prf:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\precompile_header.prf:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\warn_on.prf:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\qt.prf:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\resources_functions.prf:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\resources.prf:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\moc.prf:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\win32\opengl.prf:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\uic.prf:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\qmake_use.prf:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\file_copies.prf:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\win32\windows.prf:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\testcase_targets.prf:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\exceptions.prf:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\yacc.prf:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\lex.prf:
Zahoreni_zdroju.pro:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\lib\Qt6PrintSupport.prl:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\lib\Qt6Widgets.prl:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\lib\Qt6Gui.prl:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\lib\Qt6Core.prl:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\lib\Qt6EntryPoint.prl:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\mkspecs\features\build_pass.prf:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\lib\Qt6PrintSupportd.prl:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\lib\Qt6Widgetsd.prl:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\lib\Qt6Guid.prl:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\lib\Qt6Cored.prl:
D:\Qt\Tools\QtDesignStudio\qt6_design_studio_reduced_version\lib\Qt6EntryPointd.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Zahoreni_zdroju.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash

release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
